### ISSUE TITLE
[已找到，需要功能 proxy]⚠️提示"连接WebDriver错误，请检查参数是否正确或对应的WebDriver是否已开启"

### ISSUE THREAD

**Issue by NEWGAMER009** [ChengCY-2254/shuba#3]
用的windows版本。
使用流程如下：以下所有解压路径不含中文名
1、Releases里下载0.1windows版，随意盘符解压
2、根据readme里的超链接去下载了webdrive，并随意盘符解压，并启动，提示启动成功，如图
![w](https://github.com/user-attachments/assets/1e722623-4f88-459b-9899-970461cf20c9)
3、shell执行命令，提示"连接WebDriver错误，请检查参数是否正确或对应的WebDriver是否已开启"，如图
![e](https://github.com/user-attachments/assets/d708aba7-4972-4545-975a-40f3784ed7be)

**Comment by ChengCY-2254** [comment]
看起来像是端口无法连接，在用浏览器打开http://localhost:9515 看一看有没有这种数据。

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/b610c93a-ac30-497a-88be-59db5c19c9c3">

**Comment by NEWGAMER009** [comment]
> http://localhost:9515
有的：
![ee](https://github.com/user-attachments/assets/bf3a6a52-92ed-4c7d-bdf0-7636a2a52969)

**Comment by ChengCY-2254** [comment]
要不试试最新构建？我在我朋友的电脑上可以正常进行连接和抓取，最新的构建里面我把错误打印出来了，如果再出现错误的话，麻烦提交一下日志。 

[shuba-download-Windows.zip](https://github.com/user-attachments/files/16451277/shuba-download-Windows.zip)

**Comment by NEWGAMER009** [comment]
> 要不试试最新构建？我在我朋友的电脑上可以正常进行连接和抓取，最新的构建里面我把错误打印出来了，如果再出现错误的话，麻烦提交一下日志。
> 
> [shuba-download-Windows.zip](https://github.com/user-attachments/files/16451277/shuba-download-Windows.zip)

新的提示503：
![eee](https://github.com/user-attachments/assets/1854dfad-4efc-4758-b821-f1c74929d043)
这网站是要开魔法才能打开，会和开着魔法有关？

**Comment by ChengCY-2254** [comment]
> > 要不试试最新构建？我在我朋友的电脑上可以正常进行连接和抓取，最新的构建里面我把错误打印出来了，如果再出现错误的话，麻烦提交一下日志。
> > [shuba-download-Windows.zip](https://github.com/user-attachments/files/16451277/shuba-download-Windows.zip)
> 
> 新的提示503： ![eee](https://private-user-images.githubusercontent.com/25839494/354110197-1854dfad-4efc-4758-b821-f1c74929d043.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwODksIm5iZiI6MTcyMjQ5NDc4OSwicGF0aCI6Ii8yNTgzOTQ5NC8zNTQxMTAxOTctMTg1NGRmYWQtNGVmYy00NzU4LWI4MjEtZjFjNzQ5MjlkMDQzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjE5Yzk4ZGUyNDlkMzNlMWMyMDBlYzAxNTExMmZkYWIwZjcyNDVjYzdjNjI2ZjA1MWVmNWZmZWMzNWQzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_tuIt5LxwS9pSBrk16AG9i86vyUQ0-Vy89rgT1B-9k) 这网站是要开魔法才能打开，会和开着魔法有关？

69shuba是要魔法才能开来着，但你这是webDriver无法连接，就很怪。

试试在启动WebDriver的时候换一个端口，抓取的时候指定一下WebDriver的端口号。

```shell 
msedgedriver.exe --port=8080
```

```shell
./shuba -a http://localhost:8080 -l https://69shuba.cx/book/43314/
```

**Comment by NEWGAMER009** [comment]
> > > 要不试试最新构建？我在我朋友的电脑上可以正常进行连接和抓取，最新的构建里面我把错误打印出来了，如果再出现错误的话，麻烦提交一下日志。
> > > [shuba-download-Windows.zip](https://github.com/user-attachments/files/16451277/shuba-download-Windows.zip)
> > 
> > 
> > 新的提示503： ![eee](https://private-user-images.githubusercontent.com/25839494/354110197-1854dfad-4efc-4758-b821-f1c74929d043.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwODksIm5iZiI6MTcyMjQ5NDc4OSwicGF0aCI6Ii8yNTgzOTQ5NC8zNTQxMTAxOTctMTg1NGRmYWQtNGVmYy00NzU4LWI4MjEtZjFjNzQ5MjlkMDQzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZjE5Yzk4ZGUyNDlkMzNlMWMyMDBlYzAxNTExMmZkYWIwZjcyNDVjYzdjNjI2ZjA1MWVmNWZmZWMzNWQzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V_tuIt5LxwS9pSBrk16AG9i86vyUQ0-Vy89rgT1B-9k) 这网站是要开魔法才能打开，会和开着魔法有关？
> 
> 69shuba是要魔法才能开来着，但你这是webDriver无法连接，就很怪。
> 
> 试试在启动WebDriver的时候换一个端口，抓取的时候指定一下WebDriver的端口号。
> 
> ```shell
> msedgedriver.exe --port=8080
> ```
> 
> ```shell
> ./shuba -a http://localhost:8080 -l https://69shuba.cx/book/43314/
> ```

换了端口一样的503错误

**Comment by ChengCY-2254** [comment]
你的WebDriver驱动版本和Edge的版本是多少？我有点怀疑是版本不匹配。

**Comment by NEWGAMER009** [comment]
> 你的WebDriver驱动版本和Edge的版本是多少？我有点怀疑是版本不匹配。
有考虑过，但是版本是能对上的
![eeee](https://github.com/user-attachments/assets/1d916e95-578d-44ec-b511-88b567b8649e)

**Comment by ChengCY-2254** [comment]
我现在怀疑起代理了，你看看禁用代理后连接是否正常。
或者换一个Driver来尝试，例如chrome的Driver。

我去看看能不能添加一个代理参数。

**Comment by NEWGAMER009** [comment]
> 我现在怀疑起代理了，你看看禁用代理后连接是否正常。 或者换一个Driver来尝试，例如chrome的Driver。
> 
> 我去看看能不能添加一个代理参数。

还真就魔法问题，关闭以后关联式正常了，但是这网站关了又连接不上，用的V2魔法
![asd](https://github.com/user-attachments/assets/507c4001-4f9a-4069-b9c5-7f4c79a88977)

**Comment by ChengCY-2254** [comment]
> > 我现在怀疑起代理了，你看看禁用代理后连接是否正常。 或者换一个Driver来尝试，例如chrome的Driver。
> > 我去看看能不能添加一个代理参数。
> 
> 还真就魔法问题，关闭以后关联式正常了，但是这网站关了又连接不上，用的V2魔法 ![asd](https://private-user-images.githubusercontent.com/25839494/354131450-507c4001-4f9a-4069-b9c5-7f4c79a88977.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTg4NTcsIm5iZiI6MTcyMjQ5ODU1NywicGF0aCI6Ii8yNTgzOTQ5NC8zNTQxMzE0NTAtNTA3YzQwMDEtNGY5YS00MDY5LWI5YzUtN2Y0Yzc5YTg4OTc3LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA3NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNDJmNmExZGI5MGZiOTI5MDExOTczZmRmNjgyYmE0YzFhMWI0MWM4MjI1Y2E5Y2M4NTM1OTdlNjYzMWM5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hV1RJOZJm5-SHloPyoIXfc8rRvdvZtCHkqH5B7umSKw)

我去研究研究这玩意怎么加入代理，文档里写得过于模糊不清了。
