### ISSUE TITLE
下载内容存在段落丢失现象

### ISSUE THREAD

**Issue by NEWGAMER009** [ChengCY-2254/shuba#5]
和0.1版本相比，0.2版本能正常使用了。但是发现一些章节会出现段落丢失现象，也就是一些章节正常一些章节又是正常的。
    丢失的段落主要集中在两个地方：1、章节第一段句子。2、章节中间的一段句子。
    举例：
    具体章节链接：https://69shuba.cx/txt/43305/38749658
    1、第一段句子丢失如图：
![1](https://github.com/user-attachments/assets/fa61c7a9-8388-4ff1-a434-5b80d18180c4)
    2、第二段句子丢失如图：
![2](https://github.com/user-attachments/assets/91b5b250-caaf-4048-b732-85d93db9bbb9)

    通过和能正常下载章节，在F12下查看，发现有一点区别。
    举例：
    正常下载章节链接：https://69shuba.cx/txt/43305/32688793
    1、第一段比较，发现没有使用p标签，如图：
![3](https://github.com/user-attachments/assets/5648b391-c21a-4fa2-980e-a43672a30958)
    2、中间丢失段落，看着标签内容是一样的，但是不知道为什么后者会丢失此段句子，如图：
![4](https://github.com/user-attachments/assets/a2ba5818-1060-462a-8fa8-1ae76e2ca691)

**Comment by ChengCY-2254** [comment]
已在 https://github.com/ChengCY-2254/shuba/commit/2b02a663acbc6bea88e51b2bb085233837404f2d 中修复。
[下载构建](https://github.com/ChengCY-2254/shuba/actions/runs/10258787587)

**Comment by NEWGAMER009** [comment]
> 已在 [2b02a66](https://github.com/ChengCY-2254/shuba/commit/2b02a663acbc6bea88e51b2bb085233837404f2d) 中修复。 [下载构建](https://github.com/ChengCY-2254/shuba/actions/runs/10258787587)

每章的章节名丢失。
例子：
本来格式：
第一章 xxx
第一章内容
第二章 xxx
第二章内容

现在丢失的章节变成：
第一章内容
第二章内容

**Comment by ChengCY-2254** [comment]
> > 已在 [2b02a66](https://github.com/ChengCY-2254/shuba/commit/2b02a663acbc6bea88e51b2bb085233837404f2d) 中修复。 [下载构建](https://github.com/ChengCY-2254/shuba/actions/runs/10258787587)
> 
> 每章的章节名丢失。 例子： 本来格式： 第一章 xxx 第一章内容 第二章 xxx 第二章内容
> 
> 现在丢失的章节变成： 第一章内容 第二章内容

能给一个抓取丢失的url吗？
有些书可能格式不太一样。

**Comment by NEWGAMER009** [comment]
> > > 已在 [2b02a66](https://github.com/ChengCY-2254/shuba/commit/2b02a663acbc6bea88e51b2bb085233837404f2d) 中修复。 [下载构建](https://github.com/ChengCY-2254/shuba/actions/runs/10258787587)
> > 
> > 
> > 每章的章节名丢失。 例子： 本来格式： 第一章 xxx 第一章内容 第二章 xxx 第二章内容
> > 现在丢失的章节变成： 第一章内容 第二章内容
> 
> 能给一个抓取丢失的url吗？ 有些书可能格式不太一样。

https://69shuba.cx/book/43314/

**Comment by ChengCY-2254** [comment]
并没有观察到该现象，这是我抓取后随机截取的章节名。
<img width="865" alt="image" src="https://github.com/user-attachments/assets/00bbcbc5-069e-41d9-8d1a-d26db8295daa">
<img width="892" alt="image" src="https://github.com/user-attachments/assets/f29fbdfe-e0bc-4828-bf0c-cedf8a25cdeb">

**Comment by NEWGAMER009** [comment]
> 并没有观察到该现象，这是我抓取后随机截取的章节名。 <img alt="image" width="865" src="https://private-user-images.githubusercontent.com/61931277/355476331-00bbcbc5-069e-41d9-8d1a-d26db8295daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI5NzMsIm5iZiI6MTcyMjk1MjY3MywicGF0aCI6Ii82MTkzMTI3Ny8zNTU0NzYzMzEtMDBiYmNiYzUtMDY5ZS00MWQ5LThkMWEtZDI2ZGI4Mjk1ZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmZiY2FjN2ZiZTJiNzY5NmIxODgzZDcxODA0NmMyZmY1NjhiNjdhZmViOTg0ZDI5MjI4MzBkYjg0OWZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_VaM8KovtFWRxojV0_DLmARlTCgp4WHcvfVV2gz9ZY"> <img alt="image" width="892" src="https://private-user-images.githubusercontent.com/61931277/355476479-f29fbdfe-e0bc-4828-bf0c-cedf8a25cdeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI5NzMsIm5iZiI6MTcyMjk1MjY3MywicGF0aCI6Ii82MTkzMTI3Ny8zNTU0NzY0NzktZjI5ZmJkZmUtZTBiYy00ODI4LWJmMGMtY2VkZjhhMjVjZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTBiMmFmYWNiN2YzN2YxZTNlOTY0OTUwNjViNGM5YmIwZjE4YzNiZGYyNWZkZmZjNzE1MjZiMzA3YzZhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwdvOmTtki17PJPlJM-fJ_Mihu7NUDmnCUEqn_xK8A8">

使用的是2b02a66这个版本吗？

**Comment by ChengCY-2254** [comment]
> > 并没有观察到该现象，这是我抓取后随机截取的章节名。 <img alt="image" width="865" src="https://private-user-images.githubusercontent.com/61931277/355476331-00bbcbc5-069e-41d9-8d1a-d26db8295daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI5NzMsIm5iZiI6MTcyMjk1MjY3MywicGF0aCI6Ii82MTkzMTI3Ny8zNTU0NzYzMzEtMDBiYmNiYzUtMDY5ZS00MWQ5LThkMWEtZDI2ZGI4Mjk1ZGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YmZiY2FjN2ZiZTJiNzY5NmIxODgzZDcxODA0NmMyZmY1NjhiNjdhZmViOTg0ZDI5MjI4MzBkYjg0OWZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_VaM8KovtFWRxojV0_DLmARlTCgp4WHcvfVV2gz9ZY"> <img alt="image" width="892" src="https://private-user-images.githubusercontent.com/61931277/355476479-f29fbdfe-e0bc-4828-bf0c-cedf8a25cdeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI5NzMsIm5iZiI6MTcyMjk1MjY3MywicGF0aCI6Ii82MTkzMTI3Ny8zNTU0NzY0NzktZjI5ZmJkZmUtZTBiYy00ODI4LWJmMGMtY2VkZjhhMjVjZGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNTc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTBiMmFmYWNiN2YzN2YxZTNlOTY0OTUwNjViNGM5YmIwZjE4YzNiZGYyNWZkZmZjNzE1MjZiMzA3YzZhYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwdvOmTtki17PJPlJM-fJ_Mihu7NUDmnCUEqn_xK8A8">
> 
> 使用的是2b02a66这个版本吗？

是最新的构建，不过我在早上提交2b02a66后就没有动过这里的逻辑，后续变动的都是代码结构，为支持更多网站做准备。
刚才下回了[2b02a66](https://github.com/ChengCY-2254/shuba/commit/2b02a663acbc6bea88e51b2bb085233837404f2d)构建并重新进行了抓取操作，没有发现章节名丢失现象。

**Comment by NEWGAMER009** [comment]
那就很奇怪，这是我这边下载的结果，第一章开始全部丢失章节名，下面是第一章
![aaaa](https://github.com/user-attachments/assets/d389a513-f6ee-408c-86eb-8dc108de592a)

换了几个其它链接，一样是没有章节的

**Comment by ChengCY-2254** [comment]
> 那就很奇怪，这是我这边下载的结果，第一章开始全部丢失章节名，下面是第一章 ![aaaa](https://private-user-images.githubusercontent.com/25839494/355480534-d389a513-f6ee-408c-86eb-8dc108de592a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM2MDYsIm5iZiI6MTcyMjk1MzMwNiwicGF0aCI6Ii8yNTgzOTQ5NC8zNTU0ODA1MzQtZDM4OWE1MTMtZjZlZS00MDhjLTg2ZWItOGRjMTA4ZGU1OTJhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDRjNGQwZmU2YWMyZTU5Yjg4ZTNlYjE3YjcyM2RjZTFmYmJiNzM2NDcyOTE4NTg1OWM0NDcxNDY3ZDljZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ns-V0B_S0tJAsSNxdnsKlyafArKhiB5pIGA5dAOcKCo)
> 
> 换了几个其它链接，一样是没有章节的

我去借用一下我朋友的电脑看一看是什么情况。
可能是windows水土不服？
你先试试最新构建。[f154c18](https://github.com/ChengCY-2254/shuba/actions/runs/10260784420)

**Comment by NEWGAMER009** [comment]
> > 那就很奇怪，这是我这边下载的结果，第一章开始全部丢失章节名，下面是第一章 ![aaaa](https://private-user-images.githubusercontent.com/25839494/355480534-d389a513-f6ee-408c-86eb-8dc108de592a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM2MDYsIm5iZiI6MTcyMjk1MzMwNiwicGF0aCI6Ii8yNTgzOTQ5NC8zNTU0ODA1MzQtZDM4OWE1MTMtZjZlZS00MDhjLTg2ZWItOGRjMTA4ZGU1OTJhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDRjNGQwZmU2YWMyZTU5Yjg4ZTNlYjE3YjcyM2RjZTFmYmJiNzM2NDcyOTE4NTg1OWM0NDcxNDY3ZDljZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ns-V0B_S0tJAsSNxdnsKlyafArKhiB5pIGA5dAOcKCo)
> > 换了几个其它链接，一样是没有章节的
> 
> 我去借用一下我朋友的电脑看一看是什么情况。 可能是windows水土不服？ 你先试试最新构建。[f154c18](https://github.com/ChengCY-2254/shuba/actions/runs/10260784420)

最新构建同样情况，换成最早的0.2版本章节名倒是正常的

**Comment by ChengCY-2254** [comment]
> > > 那就很奇怪，这是我这边下载的结果，第一章开始全部丢失章节名，下面是第一章 ![aaaa](https://private-user-images.githubusercontent.com/25839494/355480534-d389a513-f6ee-408c-86eb-8dc108de592a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTM2MDYsIm5iZiI6MTcyMjk1MzMwNiwicGF0aCI6Ii8yNTgzOTQ5NC8zNTU0ODA1MzQtZDM4OWE1MTMtZjZlZS00MDhjLTg2ZWItOGRjMTA4ZGU1OTJhLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDRjNGQwZmU2YWMyZTU5Yjg4ZTNlYjE3YjcyM2RjZTFmYmJiNzM2NDcyOTE4NTg1OWM0NDcxNDY3ZDljZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ns-V0B_S0tJAsSNxdnsKlyafArKhiB5pIGA5dAOcKCo)
> > > 换了几个其它链接，一样是没有章节的
> > 
> > 
> > 我去借用一下我朋友的电脑看一看是什么情况。 可能是windows水土不服？ 你先试试最新构建。[f154c18](https://github.com/ChengCY-2254/shuba/actions/runs/10260784420)
> 
> 最新构建同样情况，换成最早的0.2版本章节名倒是正常的

~~大概是找到原因了吧，不是全屏的格式不一样。并且我发现windows下我的书名也没了，还真是水土不服。
标题没锁定到h1是因为我看到下面标题蛮合适的，所以就用的下面的标题。~~
已找到问题，就是窗口大小问题
